<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Package;
use App\Models\Role;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        // Safe clear of existing client tables
        DB::table('client_api_keys')->delete();
        DB::table('client_channels')->delete();
        DB::table('client_packages')->delete();
        DB::table('client_users')->delete();
        DB::table('clients')->delete();

        $clientRoleId = Role::where('name', 'Client Bangla (Without AP)')->value('id')
            ?? Role::where('type', 'client')->value('id')
            ?? Role::first()?->id;

        $pkgPremium = Package::where('code', 'PREMIUM-BUNDLE')->first();
        $pkgStandard = Package::where('code', 'STANDARD-NEWS')->first();
        $pkgBasic = Package::where('code', 'BASIC-NEWS')->first();

        $clientsData = [
            [
                'name' => 'The Daily Star',
                'code' => 'DST',
                'ini' => 'DS',
                'grad' => 'g1',
                'type' => 'newspaper',
                'display_type' => 'National English daily',
                'city' => 'Dhaka',
                'tier' => 'Premium',
                'status' => 'active',
                'package_id' => $pkgPremium?->id,
                'package_name' => 'Premium Wire + Media',
                'addons' => ['AP World pack', 'Bangla service'],
                'renew_days' => 37,
                'renewal_date' => Carbon::now()->addDays(37),
                'since' => 'Mar 2014',
                'billing_email' => 'billing@thedailystar.net',
                'notes' => 'Prefers XML push for breaking news. Renew with AP pack upsell conversation.',
                'usage' => ['dl' => 1284, 'quota' => 2000, 'api' => '41.2k', 'last' => '12 min ago'],
                'contacts' => [
                    ['n' => 'News Desk', 'r' => '24/7 desk', 'e' => 'newsdesk@thedailystar.net'],
                    ['n' => 'Rahim Uddin', 'r' => 'Digital head', 'e' => 'rahim@thedailystar.net'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['newsdesk@thedailystar.net', 'city@thedailystar.net'], 'health' => 'ok'],
                    'ftp' => ['on' => true, 'host' => '103.118.19.26', 'user' => 'unb', 'port' => '21', 'pass' => 'Ds@Unb321', 'health' => 'ok'],
                    'api' => ['on' => true, 'key' => 'unb_live_7f3a9d2c4b8e1a6f', 'webhook' => 'https://api.thedailystar.net/unb-hook', 'health' => 'ok'],
                ],
                'activity' => [
                    ['c' => '#16a34a', 't' => 'Downloaded 3 photos from the archive', 'w' => '32 min ago'],
                    ['c' => '#3b6fe0', 't' => 'API key regenerated by client admin', 'w' => '2 days ago'],
                    ['c' => '#16a34a', 't' => 'Package renewed — Premium Wire + Media', 'w' => 'Aug 1, 2026'],
                ],
            ],
            [
                'name' => 'Prothom Alo',
                'code' => 'PAL',
                'ini' => 'PA',
                'grad' => 'g2',
                'type' => 'newspaper',
                'display_type' => 'National daily',
                'city' => 'Dhaka',
                'tier' => 'Premium',
                'status' => 'active',
                'package_id' => $pkgPremium?->id,
                'package_name' => 'Premium Wire + Media',
                'addons' => ['Bangla service'],
                'renew_days' => 82,
                'renewal_date' => Carbon::now()->addDays(82),
                'since' => 'Jan 2012',
                'billing_email' => 'cne@prothomalo.com',
                'notes' => '',
                'usage' => ['dl' => 962, 'quota' => 2000, 'api' => '—', 'last' => '1 hr ago'],
                'contacts' => [
                    ['n' => 'Chief News Editor', 'r' => 'Desk', 'e' => 'cne@prothomalo.com'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['cne@prothomalo.com'], 'health' => 'ok'],
                    'ftp' => ['on' => true, 'host' => '203.82.197.181', 'user' => 'palounb', 'port' => '21', 'pass' => 'Pa#8821lm', 'health' => 'ok'],
                    'api' => ['on' => false, 'key' => '', 'webhook' => '', 'health' => 'off'],
                ],
                'activity' => [
                    ['c' => '#16a34a', 't' => 'FTP push completed — morning bundle (14 stories)', 'w' => '6 hr ago'],
                ],
            ],
            [
                'name' => 'Jugantor',
                'code' => 'JUG',
                'ini' => 'JU',
                'grad' => 'g4',
                'type' => 'newspaper',
                'display_type' => 'National daily',
                'city' => 'Dhaka',
                'tier' => 'Standard',
                'status' => 'active',
                'package_id' => $pkgStandard?->id,
                'package_name' => 'Standard Wire',
                'addons' => [],
                'renew_days' => 9,
                'renewal_date' => Carbon::now()->addDays(9),
                'since' => 'Jun 2016',
                'billing_email' => 'it@jugantor.com',
                'notes' => 'FTP failing since yesterday — client IT notified, waiting on firewall whitelist.',
                'usage' => ['dl' => 311, 'quota' => 800, 'api' => '—', 'last' => '3 hr ago'],
                'contacts' => [
                    ['n' => 'IT Cell', 'r' => 'Technical', 'e' => 'it@jugantor.com'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['it@jugantor.com'], 'health' => 'ok'],
                    'ftp' => ['on' => true, 'host' => 'ftp.jugantor.com', 'user' => 'jug_unb', 'port' => '21', 'pass' => 'Jg!2210x', 'health' => 'fail'],
                    'api' => ['on' => false, 'key' => '', 'webhook' => '', 'health' => 'off'],
                ],
                'activity' => [
                    ['c' => '#e5484d', 't' => 'FTP upload failed — auth timeout (auto-retry scheduled)', 'w' => '1 hr ago'],
                    ['c' => '#f0a832', 't' => 'Renewal reminder sent — expires in 9 days', 'w' => '2 days ago'],
                ],
            ],
            [
                'name' => 'Bangladesh Today',
                'code' => 'BTD',
                'ini' => 'BT',
                'grad' => 'g6',
                'type' => 'newspaper',
                'display_type' => 'English daily',
                'city' => 'Dhaka',
                'tier' => 'Standard',
                'status' => 'suspended', // paused
                'pause_reason' => 'Payment hold',
                'package_id' => $pkgStandard?->id,
                'package_name' => 'Standard Wire',
                'addons' => [],
                'renew_days' => 56,
                'renewal_date' => Carbon::now()->addDays(56),
                'since' => 'Sep 2018',
                'billing_email' => 'accounts@bangladeshtoday.net',
                'notes' => 'Paused over July invoice. Accounts following up; MD assured payment by Eid.',
                'usage' => ['dl' => 88, 'quota' => 800, 'api' => '3.1k', 'last' => '5 days ago'],
                'contacts' => [
                    ['n' => 'Accounts', 'r' => 'Billing', 'e' => 'accounts@bangladeshtoday.net'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['accounts@bangladeshtoday.net'], 'health' => 'ok'],
                    'ftp' => ['on' => false, 'host' => '', 'user' => '', 'port' => '21', 'pass' => '', 'health' => 'off'],
                    'api' => ['on' => true, 'key' => 'unb_live_2c8d4e9f1a3b5d7c', 'webhook' => 'https://cms.bangladeshtoday.net/hooks/unb', 'health' => 'ok'],
                ],
                'activity' => [
                    ['c' => '#f0a832', 't' => 'Deliveries paused — reason: Payment hold', 'w' => '5 days ago'],
                    ['c' => '#3b6fe0', 't' => 'Invoice #INV-2291 sent', 'w' => '12 days ago'],
                ],
            ],
            [
                'name' => 'The Daily Ittefaq',
                'code' => 'ITF',
                'ini' => 'IT',
                'grad' => 'g5',
                'type' => 'newspaper',
                'display_type' => 'National daily',
                'city' => 'Dhaka',
                'tier' => 'Standard',
                'status' => 'active',
                'package_id' => $pkgStandard?->id,
                'package_name' => 'Standard Wire',
                'addons' => ['Bangla service'],
                'renew_days' => 139,
                'renewal_date' => Carbon::now()->addDays(139),
                'since' => 'Apr 2015',
                'billing_email' => 'newsroom@ittefaq.com.bd',
                'notes' => '',
                'usage' => ['dl' => 542, 'quota' => 800, 'api' => '—', 'last' => '26 min ago'],
                'contacts' => [
                    ['n' => 'Newsroom', 'r' => 'Desk', 'e' => 'newsroom@ittefaq.com.bd'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['newsroom@ittefaq.com.bd'], 'health' => 'ok'],
                    'ftp' => ['on' => true, 'host' => '103.42.11.9', 'user' => 'itfunb', 'port' => '22', 'pass' => 'Itf@2209s', 'health' => 'ok'],
                    'api' => ['on' => false, 'key' => '', 'webhook' => '', 'health' => 'off'],
                ],
                'activity' => [
                    ['c' => '#16a34a', 't' => 'SFTP push completed — evening bundle', 'w' => '2 hr ago'],
                ],
            ],
            [
                'name' => 'Dhaka Tribune',
                'code' => 'DTB',
                'ini' => 'DT',
                'grad' => 'g3',
                'type' => 'newspaper',
                'display_type' => 'English daily',
                'city' => 'Dhaka',
                'tier' => 'Premium',
                'status' => 'active',
                'package_id' => $pkgPremium?->id,
                'package_name' => 'Premium Wire + Media',
                'addons' => ['AP World pack'],
                'renew_days' => 34,
                'renewal_date' => Carbon::now()->addDays(34),
                'since' => 'Nov 2019',
                'billing_email' => 'digital@dhakatribune.com',
                'notes' => 'Heavy API consumer — fully digital workflow, no FTP.',
                'usage' => ['dl' => 1740, 'quota' => 2000, 'api' => '58.7k', 'last' => '4 min ago'],
                'contacts' => [
                    ['n' => 'Digital Desk', 'r' => 'Online', 'e' => 'digital@dhakatribune.com'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['digital@dhakatribune.com'], 'health' => 'ok'],
                    'ftp' => ['on' => false, 'host' => '', 'user' => '', 'port' => '21', 'pass' => '', 'health' => 'off'],
                    'api' => ['on' => true, 'key' => 'unb_live_9e1f3a5c7b2d4f6a', 'webhook' => 'https://api.dhakatribune.com/unb', 'health' => 'ok'],
                ],
                'activity' => [
                    ['c' => '#16a34a', 't' => 'API pulled UNB Photos showcase feed', 'w' => '18 min ago'],
                ],
            ],
            [
                'name' => 'Samakal',
                'code' => 'SMK',
                'ini' => 'SM',
                'grad' => 'g7',
                'type' => 'newspaper',
                'display_type' => 'National daily',
                'city' => 'Dhaka',
                'tier' => 'Basic',
                'status' => 'suspended', // paused
                'pause_reason' => 'Client requested',
                'package_id' => $pkgBasic?->id,
                'package_name' => 'Basic Headlines',
                'addons' => [],
                'renew_days' => 102,
                'renewal_date' => Carbon::now()->addDays(102),
                'since' => 'Feb 2020',
                'billing_email' => 'desk@samakal.com',
                'notes' => 'Client asked to pause while they migrate CMS. Check back mid-September.',
                'usage' => ['dl' => 12, 'quota' => 200, 'api' => '—', 'last' => '2 wks ago'],
                'contacts' => [
                    ['n' => 'Desk', 'r' => 'News', 'e' => 'desk@samakal.com'],
                ],
                'channels' => [
                    'email' => ['on' => true, 'list' => ['desk@samakal.com'], 'health' => 'ok'],
                    'ftp' => ['on' => false, 'host' => '', 'user' => '', 'port' => '21', 'pass' => '', 'health' => 'off'],
                    'api' => ['on' => false, 'key' => '', 'webhook' => '', 'health' => 'off'],
                ],
                'activity' => [
                    ['c' => '#f0a832', 't' => 'Deliveries paused — reason: Client requested', 'w' => '2 wks ago'],
                ],
            ],
            [
                'name' => 'The Financial Express',
                'code' => 'TFE',
                'ini' => 'FE',
                'grad' => 'g8',
                'type' => 'newspaper',
                'display_type' => 'Business daily',
                'city' => 'Dhaka',
                'tier' => 'Standard',
                'status' => 'closed', // deactivated
                'package_id' => $pkgStandard?->id,
                'package_name' => 'Standard Wire',
                'addons' => [],
                'renew_days' => 999,
                'renewal_date' => null,
                'since' => 'May 2013',
                'billing_email' => 'desk@thefinancialexpress.com.bd',
                'notes' => 'Offboarded Mar 2026 — moved to competitor. Keep records; win-back target for Q4.',
                'usage' => ['dl' => 0, 'quota' => 800, 'api' => '—', 'last' => '—'],
                'contacts' => [
                    ['n' => 'Former desk', 'r' => '—', 'e' => 'desk@thefinancialexpress.com.bd'],
                ],
                'channels' => [
                    'email' => ['on' => false, 'list' => [], 'health' => 'off'],
                    'ftp' => ['on' => false, 'host' => '', 'user' => '', 'port' => '21', 'pass' => '', 'health' => 'off'],
                    'api' => ['on' => false, 'key' => '', 'webhook' => '', 'health' => 'off'],
                ],
                'activity' => [
                    ['c' => '#7c7f8c', 't' => 'Client deactivated — contract ended', 'w' => 'Mar 30, 2026'],
                ],
            ],
        ];

        foreach ($clientsData as $c) {
            $clientId = DB::table('clients')->insertGetId([
                'public_id' => (string) Str::ulid(),
                'name' => $c['name'],
                'code' => $c['code'],
                'type' => $c['type'],
                'country' => 'BD',
                'timezone' => 'Asia/Dhaka',
                'status' => $c['status'],
                'billing_email' => $c['billing_email'],
                'notes' => json_encode([
                    'ini' => $c['ini'],
                    'grad' => $c['grad'],
                    'display_type' => $c['display_type'],
                    'city' => $c['city'],
                    'tier' => $c['tier'],
                    'since' => $c['since'],
                    'addons' => $c['addons'],
                    'usage' => $c['usage'],
                    'note_text' => $c['notes'],
                    'pause_reason' => $c['pause_reason'] ?? null,
                    'activity' => $c['activity'],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Seed Users
            foreach ($c['contacts'] as $contact) {
                DB::table('client_users')->insert([
                    'client_id' => $clientId,
                    'name' => $contact['n'],
                    'email' => $contact['e'],
                    'password' => Hash::make('password'),
                    'client_role_id' => $clientRoleId,
                    'status' => $c['status'] === 'closed' ? 'deactivated' : 'active',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }

            // Seed Channels
            if ($c['channels']['ftp']['on']) {
                $isFail = $c['channels']['ftp']['health'] === 'fail';
                DB::table('client_channels')->insert([
                    'client_id' => $clientId,
                    'type' => 'ftp',
                    'config' => json_encode([
                        'host' => $c['channels']['ftp']['host'],
                        'username' => $c['channels']['ftp']['user'],
                        'port' => $c['channels']['ftp']['port'],
                        'password' => $c['channels']['ftp']['pass'],
                        'health' => $c['channels']['ftp']['health'],
                    ]),
                    'status' => $c['status'] === 'closed' ? 'disabled' : 'active',
                    'failure_count' => $isFail ? 3 : 0,
                    'last_success_at' => $isFail ? now()->subDay() : now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }

            if ($c['channels']['api']['on']) {
                DB::table('client_channels')->insert([
                    'client_id' => $clientId,
                    'type' => 'api',
                    'config' => json_encode([
                        'endpoint' => $c['channels']['api']['webhook'] ?: 'https://api.unb.com.bd',
                        'key' => $c['channels']['api']['key'],
                        'webhook' => $c['channels']['api']['webhook'],
                        'health' => $c['channels']['api']['health'],
                    ]),
                    'status' => $c['status'] === 'closed' ? 'disabled' : 'active',
                    'failure_count' => 0,
                    'last_success_at' => now(),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);

                if (! empty($c['channels']['api']['key'])) {
                    DB::table('client_api_keys')->insert([
                        'client_id' => $clientId,
                        'name' => 'Default Wire API Key',
                        'key_hash' => hash('sha256', $c['channels']['api']['key']),
                        'scopes' => json_encode(['feed:read', 'media:download']),
                        'rate_limit_rpm' => 60,
                        'created_at' => now(),
                    ]);
                }
            }

            // Seed Package Subscription
            if ($c['package_id']) {
                DB::table('client_packages')->insert([
                    'client_id' => $clientId,
                    'package_id' => $c['package_id'],
                    'starts_at' => Carbon::now()->subMonths(6),
                    'ends_at' => $c['renewal_date'],
                    'status' => $c['status'] === 'closed' ? 'expired' : 'active',
                    'created_at' => now(),
                ]);
            }

            // Seed Add-on Subscriptions
            foreach ($c['addons'] as $addonName) {
                $addonPkg = Package::where('name', $addonName)->first();
                if ($addonPkg) {
                    DB::table('client_packages')->insert([
                        'client_id' => $clientId,
                        'package_id' => $addonPkg->id,
                        'starts_at' => Carbon::now()->subMonths(6),
                        'ends_at' => $c['renewal_date'],
                        'status' => $c['status'] === 'closed' ? 'expired' : 'active',
                        'created_at' => now(),
                    ]);
                }
            }
        }
    }
}
