import {
  WireStory,
  MediaLibraryItem,
  GalleryItem,
  CollectionItem,
  TrendingItem,
  StreamPhotoItem,
  ClientContext,
  SavedSearch,
} from "../app/types";

export const INITIAL_STORIES: WireStory[] = [
  {
    id: 1,
    public_id: "sty_01J6H001BNP",
    mins: 8,
    category: "Politics",
    language: "en",
    published_at: new Date(Date.now() - 8 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: "you",
    has_video: true,
    headline:
      "His battleground, his fort, his home: Rizvi returns to BNP's Nayapaltan central office after elevation to top post",
    brief:
      "BNP's newly elevated leader Ruhul Kabir Rizvi returned to the party's Nayapaltan central office to a rousing welcome from activists who had waited since morning.",
    body_html:
      "<p>BNP's newly elevated leader Ruhul Kabir Rizvi returned to the party's Nayapaltan central office on Sunday, greeted by hundreds of activists who had waited outside since morning.</p><p>Speaking briefly to reporters, Rizvi said the office had always been his political home and pledged to rebuild the party's organisational strength at the grassroots.</p><p>Senior joint secretary general Ruhul Kabir Rizvi was elevated to the party's top policy-making post on Saturday night.</p>",
    tags: ["politics", "bnp", "dhaka"],
    caps: [
      "Rizvi speaks to reporters outside BNP's Nayapaltan central office — Photo: UNB",
      "BNP activists gather at Nayapaltan ahead of Rizvi's arrival — Photo: UNB",
      "Rizvi enters the party office after his elevation to the top post — Photo: UNB",
    ],
  },
  {
    id: 2,
    public_id: "sty_01J6H002BQR",
    mins: 31,
    category: "Business",
    language: "en",
    published_at: new Date(Date.now() - 31 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Bangla QR's daily transactions cross Tk 110 crore following mandatory rollout",
    brief:
      "Daily transactions through Bangla QR have crossed Tk 110 crore within weeks of the central bank making the interoperable code mandatory at merchant points.",
    body_html:
      "<p>Daily transactions through Bangla QR have crossed Tk 110 crore, Bangladesh Bank data showed, within weeks of the interoperable quick-response code being made mandatory at merchant points across the country.</p><p>Central bank officials said the interoperable system allows customers of any bank or mobile financial service to pay any merchant from a single code.</p><p>Merchant onboarding has doubled in Dhaka and Chattogram since the directive took effect.</p>",
    tags: ["bangla-qr", "economy", "banking"],
    caps: [
      "A customer pays via Bangla QR at a shop in Dhaka's New Market — Photo: UNB",
      "Bangladesh Bank headquarters in Motijheel — Photo: UNB",
    ],
  },
  {
    id: 3,
    public_id: "sty_01J6H003SWP",
    mins: 47,
    category: "Politics",
    language: "en",
    published_at: new Date(Date.now() - 47 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Swapon joins as PM's political adviser",
    brief:
      "Zahir Uddin Swapon has joined the Prime Minister's Office as political adviser, weeks after serving as information and broadcasting minister.",
    body_html:
      "<p>Zahir Uddin Swapon on Sunday joined the Prime Minister's Office as political adviser to the prime minister.</p><p>PMO officials confirmed the appointment, saying Swapon will advise on political coordination and parliamentary affairs.</p><p>Swapon previously served as information and broadcasting minister.</p>",
    tags: ["politics", "pm-office"],
    caps: ["Zahir Uddin Swapon arrives at the Prime Minister's Office — Photo: UNB"],
  },
  {
    id: 4,
    public_id: "sty_01J6H004UNB",
    mins: 68,
    category: "Bangladesh",
    language: "en",
    published_at: new Date(Date.now() - 68 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "UNB's annual District Correspondents' Conference puts onus on credible journalism",
    brief:
      "Daylong engagements on different aspects of the media landscape inaugurated by Zahir Uddin Swapon in the capital.",
    body_html:
      "<p>UNB's annual District Correspondents' Conference-2026 began in the capital on Saturday, putting the emphasis on credible, fact-based journalism at a time when misinformation travels faster than ever.</p><p>The conference featured high-level panel discussions and interactive sessions between newsroom members and district correspondents.</p><p>Awards were handed out to the best district correspondents of the past year.</p>",
    tags: ["unb", "journalism", "dhaka"],
    caps: [
      "Information minister Zahir Uddin Swapon speaks at the inaugural session of UNB's district correspondents' conference — Photo: UNB",
      "Award-winning district correspondents at the conference — Photo: UNB",
    ],
  },
  {
    id: 5,
    public_id: "sty_01J6H005POL",
    mins: 121,
    category: "World",
    language: "en",
    published_at: new Date(Date.now() - 121 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Thousands remain without power after strong winds hit Poland",
    brief:
      "Emergency crews worked through the night to restore electricity after a storm front brought down trees and power lines across central Poland.",
    body_html:
      "<p>Tens of thousands of households in central Poland remained without electricity on Sunday after strong winds brought down trees and power lines overnight.</p><p>Emergency crews restored supply to most urban areas by morning, but rural districts around Łódź were still affected.</p><p>Rail services on several regional routes were suspended pending track inspections.</p>",
    tags: ["world", "weather", "europe"],
    caps: ["Fallen trees block a road after the storm in central Poland — Photo: AP"],
  },
  {
    id: 6,
    public_id: "sty_01J6H006CHI",
    mins: 122,
    category: "World",
    language: "en",
    published_at: new Date(Date.now() - 122 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: true,
    headline: "2 dead, 4 missing after landslides in SW China's Yunnan",
    brief:
      "Rescue teams are searching for four missing people after rain-triggered landslides hit a mountain township in Yunnan province.",
    body_html:
      "<p>At least two people died and four others were missing after rain-triggered landslides struck a mountain township in southwest China's Yunnan province, local authorities said.</p><p>More than 300 rescue workers with excavators and sniffer dogs were deployed to the site.</p><p>Provincial meteorologists warned of further heavy rain over the next 48 hours.</p>",
    tags: ["world", "china", "disaster"],
    caps: [],
  },
  {
    id: 7,
    public_id: "sty_01J6H007JAP",
    mins: 123,
    category: "World",
    language: "en",
    published_at: new Date(Date.now() - 123 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "6.0-magnitude quake jolts Japan's Hokkaido: JMA",
    brief:
      "No tsunami warning was issued after the offshore quake, which shook buildings across northern Japan.",
    body_html:
      "<p>A 6.0-magnitude earthquake struck off the eastern coast of Hokkaido on Sunday, the Japan Meteorological Agency said, shaking buildings across northern Japan.</p><p>No tsunami warning was issued and there were no immediate reports of casualties or damage.</p><p>Bullet train services in the region were briefly suspended for safety checks.</p>",
    tags: ["world", "japan", "earthquake"],
    caps: [],
  },
  {
    id: 8,
    public_id: "sty_01J6H008BAG",
    mins: 185,
    category: "Environment",
    language: "en",
    published_at: new Date(Date.now() - 185 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Bishkhali riverbanks turn green as 50,000 trees reshape Bagerhat landscape",
    brief:
      "A three-year community plantation drive has transformed eroding banks of the Bishkhali river into a continuous green belt.",
    body_html:
      "<p>A three-year community plantation drive has transformed the eroding banks of the Bishkhali river in Bagerhat into a continuous green belt of 50,000 trees.</p><p>Local administration officials said the belt has measurably reduced riverbank erosion and created new livelihoods through fruit-bearing species.</p><p>The programme will be replicated in two more coastal districts next year.</p>",
    tags: ["environment", "bagerhat", "climate"],
    caps: [
      "Newly planted trees line the banks of the Bishkhali river — Photo: UNB",
      "Aerial view of the green belt in Bagerhat — Photo: UNB",
    ],
  },
  {
    id: 9,
    public_id: "sty_01J6H009MRT",
    mins: 240,
    category: "Bangladesh",
    language: "en",
    published_at: new Date(Date.now() - 240 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: "other",
    has_video: true,
    headline: "Inside the metro rail expansion: documents reveal new timeline for MRT Line-1",
    brief:
      "Exclusive documents show the revised construction schedule for the capital's first underground metro line.",
    body_html: "",
    tags: ["dhaka", "metro-rail"],
    caps: ["Construction site of MRT Line-1 at Kawran Bazar — Photo: UNB"],
  },
  {
    id: 10,
    public_id: "sty_01J6H010TIG",
    mins: 245,
    category: "Sports",
    language: "en",
    published_at: new Date(Date.now() - 245 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Tigers name squad for home Test series — two uncapped players included",
    brief:
      "The selectors rewarded domestic form, handing maiden Test call-ups to a pacer and a top-order batter.",
    body_html:
      "<p>Bangladesh on Sunday named a 15-member squad for the upcoming home Test series, handing maiden call-ups to pacer Hasan Mahmud's new-ball partner and a top-order batter after strong domestic seasons.</p><p>The series begins at the Sher-e-Bangla National Stadium next week.</p><p>The squad will assemble in Mirpur for a conditioning camp on Tuesday.</p>",
    tags: ["cricket", "tigers", "sports"],
    caps: ["Tigers train at the Sher-e-Bangla National Stadium in Mirpur — Photo: UNB"],
  },
  {
    id: 11,
    public_id: "sty_01J6H011SAV",
    mins: 320,
    category: "Bangladesh",
    language: "en",
    published_at: new Date(Date.now() - 320 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "President pays tribute to Liberation War martyrs at National Memorial in Savar",
    brief:
      "The president placed wreaths at the National Memorial and stood in solemn silence to honour the martyrs.",
    body_html:
      "<p>The president paid rich tributes to the martyrs of the Liberation War by placing wreaths at the National Memorial in Savar on Saturday morning.</p><p>He stood in solemn silence for a while as the bugle played the last post.</p><p>Senior cabinet members and service chiefs were present.</p>",
    tags: ["bangladesh", "president", "savar"],
    caps: ["The president places a wreath at the National Memorial in Savar — Photo: UNB"],
  },
  {
    id: 12,
    public_id: "sty_01J6H012REM",
    mins: 380,
    category: "Business",
    language: "en",
    published_at: new Date(Date.now() - 380 * 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Remittance inflow keeps forex reserve steady above $20bn",
    brief:
      "Expatriate Bangladeshis sent home over $2 billion for the third consecutive month, central bank data shows.",
    body_html:
      "<p>Expatriate Bangladeshis sent home more than $2 billion for the third consecutive month, keeping the gross foreign exchange reserve steady above $20 billion, Bangladesh Bank data showed.</p><p>Bankers attributed the sustained inflow to the stable exchange rate and formal-channel incentives.</p><p>The central bank expects the trend to hold through the festival season.</p>",
    tags: ["economy", "remittance", "banking"],
    caps: [],
  },
];

export const NEW_STORIES: WireStory[] = [
  {
    id: 13,
    public_id: "sty_01J6H013WTH",
    mins: 1,
    category: "Weather",
    language: "en",
    published_at: new Date(Date.now() - 60000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "Met office forecasts light rain over Dhaka, Chattogram divisions this evening",
    brief:
      "A low over the Bay is likely to bring light to moderate rain to parts of the country over the next 24 hours.",
    body_html:
      "<p>The Bangladesh Meteorological Department on Sunday forecast light to moderate rain over Dhaka and Chattogram divisions in the next 24 hours.</p><p>A low-pressure area over the northwest Bay is driving the unsettled weather, a Met office bulletin said.</p><p>Day temperatures may fall by 1–2°C across the country.</p>",
    tags: ["weather", "dhaka"],
    caps: ["Clouds gather over the capital ahead of the evening shower — Photo: UNB"],
  },
  {
    id: 14,
    public_id: "sty_01J6H014DSE",
    mins: 2,
    category: "Business",
    language: "en",
    published_at: new Date(Date.now() - 120000).toISOString(),
    status: "published",
    is_breaking: false,
    ex: null,
    has_video: false,
    headline: "DSEX closes higher as bank stocks rally for third straight session",
    brief: "The benchmark index gained 0.8 percent with turnover crossing Tk 900 crore.",
    body_html:
      "<p>The Dhaka Stock Exchange's benchmark index DSEX closed 0.8 percent higher on Sunday as bank stocks rallied for a third straight session.</p><p>Turnover crossed Tk 900 crore, the highest in two weeks.</p><p>Analysts credited renewed institutional buying in large-cap financials.</p>",
    tags: ["economy", "dse", "banking"],
    caps: [],
  },
];

export const MEDIA_ITEMS: MediaLibraryItem[] = [
  {
    id: "m1",
    src: "unb",
    type: "photo",
    grad: "g1",
    cap: "Rizvi speaks to reporters outside BNP's Nayapaltan central office",
    credit: "Photo: UNB",
    by: "Enamul Haque",
    date: "Aug 24, 2026",
    d: 0,
    loc: "Dhaka",
    dim: "3000 × 2000",
    ent: "inc",
    cat: "Politics",
  },
  {
    id: "m2",
    src: "unb",
    type: "photo",
    grad: "g4",
    cap: "A customer pays via Bangla QR at a shop in New Market",
    credit: "Photo: UNB",
    by: "Sadia Rahman",
    date: "Aug 23, 2026",
    d: 1,
    loc: "Dhaka",
    dim: "3000 × 2000",
    ent: "inc",
    cat: "Business",
  },
  {
    id: "m3",
    src: "unb",
    type: "video",
    grad: "g5",
    cap: "PM's press conference — full clip",
    credit: "UNB video",
    by: "UNB Video Desk",
    date: "Aug 23, 2026",
    d: 1,
    loc: "Dhaka",
    dim: "1080p · 01:12",
    ent: "inc",
    cat: "Politics",
  },
  {
    id: "m4",
    src: "ap",
    type: "photo",
    grad: "g6",
    cap: "Fallen trees block a road after the storm in central Poland",
    credit: "Photo: AP",
    by: "Czarek Sokolowski / AP",
    date: "Aug 23, 2026",
    d: 1,
    loc: "Warsaw, Poland",
    dim: "3500 × 2333",
    ent: "inc",
    cat: "World",
  },
  {
    id: "m5",
    src: "ap",
    type: "photo",
    grad: "g2",
    cap: "Rescue workers search the landslide site in Yunnan",
    credit: "Photo: AP",
    by: "AP Photo / Xinhua",
    date: "Aug 23, 2026",
    d: 1,
    loc: "Yunnan, China",
    dim: "3500 × 2333",
    ent: "addon",
    cat: "World",
  },
  {
    id: "m6",
    src: "ap",
    type: "photo",
    grad: "g8",
    cap: "Commuters at a Tokyo station after the Hokkaido quake",
    credit: "Photo: AP",
    by: "Kyodo via AP",
    date: "Aug 23, 2026",
    d: 1,
    loc: "Tokyo, Japan",
    dim: "3500 × 2333",
    ent: "lock",
    cat: "World",
  },
  {
    id: "m7",
    src: "unb",
    type: "photo",
    grad: "g3",
    cap: "Newly planted trees line the banks of the Bishkhali river",
    credit: "Photo: UNB",
    by: "Rashed Sumon",
    date: "Aug 22, 2026",
    d: 2,
    loc: "Bagerhat",
    dim: "3000 × 2000",
    ent: "inc",
    cat: "Environment",
  },
  {
    id: "m8",
    src: "unb",
    type: "photo",
    grad: "g7",
    cap: "Tigers train at the Sher-e-Bangla National Stadium in Mirpur",
    credit: "Photo: UNB",
    by: "Tuhin Shubhra",
    date: "Aug 22, 2026",
    d: 2,
    loc: "Dhaka",
    dim: "3000 × 2000",
    ent: "ex",
    cat: "Sports",
  },
  {
    id: "m9",
    src: "ap",
    type: "photo",
    grad: "g5",
    cap: "UN General Assembly emergency session on climate finance",
    credit: "Photo: AP",
    by: "Mary Altaffer / AP",
    date: "Aug 22, 2026",
    d: 2,
    loc: "New York, USA",
    dim: "3500 × 2333",
    ent: "emb",
    cat: "World",
  },
  {
    id: "m10",
    src: "unb",
    type: "video",
    grad: "g2",
    cap: "Padma Bridge aerial footage — morning traffic",
    credit: "UNB video",
    by: "UNB Video Desk",
    date: "Aug 22, 2026",
    d: 2,
    loc: "Mawa",
    dim: "4K · 00:48",
    ent: "inc",
    cat: "Bangladesh",
  },
  {
    id: "m11",
    src: "unb",
    type: "photo",
    grad: "g1",
    cap: "The president places a wreath at the National Memorial in Savar",
    credit: "Photo: UNB",
    by: "Enamul Haque",
    date: "Aug 22, 2026",
    d: 2,
    loc: "Savar",
    dim: "3000 × 2000",
    ent: "inc",
    cat: "Bangladesh",
  },
  {
    id: "m12",
    src: "ap",
    type: "photo",
    grad: "g4",
    cap: "Traders work the floor as Asian stocks rally on rate-cut hopes",
    credit: "Photo: AP",
    by: "AP Photo",
    date: "Aug 21, 2026",
    d: 3,
    loc: "Hong Kong",
    dim: "3500 × 2333",
    ent: "addon",
    cat: "Business",
  },
];

const GEN_POOL = [
  ["BNP standing committee in session at the Nayapaltan office", "Politics", "Dhaka"],
  ["Lawmakers arrive for the Jatiya Sangsad budget session", "Politics", "Sher-e-Bangla Nagar"],
  ["Election Commission briefing ahead of the city polls", "Politics", "Agargaon, Dhaka"],
  ["Home minister addresses senior police officials in Rajarbagh", "Politics", "Dhaka"],
  ["Morning fog settles over the Buriganga river", "Bangladesh", "Dhaka"],
  ["Commuters crowd the launch terminal at Sadarghat", "Bangladesh", "Dhaka"],
  ["Farmers harvest paddy in a flooded field", "Bangladesh", "Netrokona"],
  ["Street vendors open shop at Karwan Bazar at dawn", "Bangladesh", "Dhaka"],
  ["A rickshaw puller braves the rain in Old Dhaka", "Bangladesh", "Dhaka"],
  ["Fishermen return with the morning hilsa catch", "Bangladesh", "Chandpur"],
  ["Palestinians inspect damage after overnight strikes in Gaza", "World", "Gaza"],
  ["Ukrainian soldiers move near the front line in Donetsk", "World", "Donetsk, Ukraine"],
  ["Protesters gather outside parliament in London", "World", "London, UK"],
  ["Wildfire smoke blankets the Los Angeles skyline", "World", "Los Angeles, USA"],
  ["Voters queue at a polling station in New Delhi", "World", "New Delhi, India"],
  ["Flooded streets after monsoon rain in Manila", "World", "Manila, Philippines"],
  ["Shakib Al Hasan bowls during a training session", "Sports", "Mirpur, Dhaka"],
  ["Fans fill the gallery during the Dhaka Test", "Sports", "Mirpur, Dhaka"],
  ["Bangladesh women celebrate a wicket in the T20 series", "Sports", "Sylhet"],
  ["Footballers train at the BFF turf in Motijheel", "Sports", "Dhaka"],
  ["Trading screens glow at the Dhaka Stock Exchange", "Business", "Motijheel, Dhaka"],
  ["Garment workers on a factory floor in Ashulia", "Business", "Ashulia"],
  ["Containers stacked high at Chattogram port", "Business", "Chattogram"],
  ["Banknotes counted at a bank branch in Motijheel", "Business", "Dhaka"],
  ["A boy wades through a flooded street", "Environment", "Sylhet"],
  ["Smog hangs over the Dhaka skyline at dawn", "Environment", "Dhaka"],
  ["Sundarbans mangroves at low tide", "Environment", "Satkhira"],
  ["A Bengal monitor lizard at a wetland", "Environment", "Tangail"],
];

const GEN_BY_UNB = ["Enamul Haque", "Sadia Rahman", "Rashed Sumon", "Tuhin Shubhra", "Mahmud Hossain"];
const GEN_BY_AP = ["AP Photo", "Mary Altaffer / AP", "Czarek Sokolowski / AP", "Kyodo via AP"];
const DATE_TXT = [
  "Aug 24, 2026",
  "Aug 23, 2026",
  "Aug 22, 2026",
  "Aug 21, 2026",
  "Aug 20, 2026",
  "Aug 19, 2026",
  "Aug 18, 2026",
  "Aug 17, 2026",
  "Aug 16, 2026",
  "Aug 15, 2026",
  "Aug 14, 2026",
  "Aug 13, 2026",
  "Aug 12, 2026",
  "Aug 11, 2026",
  "Aug 10, 2026",
  "Aug 9, 2026",
  "Aug 8, 2026",
  "Aug 7, 2026",
  "Aug 6, 2026",
  "Aug 5, 2026",
  "Aug 4, 2026",
];

export function buildAllMedia(): MediaLibraryItem[] {
  const genMedia: MediaLibraryItem[] = [];
  for (let r = 0; r < 4; r++) {
    GEN_POOL.forEach((g, i) => {
      const n = r * GEN_POOL.length + i;
      const src: "unb" | "ap" = n % 3 === 2 ? "ap" : "unb";
      const vid = n % 11 === 5;
      const ent: "inc" | "addon" | "lock" | "ex" | "emb" =
        n % 13 === 6
          ? "lock"
          : n % 17 === 9
          ? "emb"
          : n % 7 === 2
          ? "addon"
          : n % 19 === 3
          ? "ex"
          : "inc";

      genMedia.push({
        id: "g" + n,
        src,
        type: vid ? "video" : "photo",
        grad: "g" + ((n % 8) + 1),
        cap: g[0],
        credit: vid ? "UNB video" : src === "ap" ? "Photo: AP" : "Photo: UNB",
        by: vid ? "UNB Video Desk" : src === "ap" ? GEN_BY_AP[n % 4] : GEN_BY_UNB[n % 5],
        date: DATE_TXT[n % DATE_TXT.length],
        d: n % DATE_TXT.length,
        loc: g[2],
        dim: vid ? "1080p · 00:" + (30 + (n % 30)) : "3000 × 2000",
        ent,
        cat: g[1],
      });
    });
  }
  return MEDIA_ITEMS.concat(genMedia);
}

export const GALLERIES: GalleryItem[] = [
  {
    id: "gal1",
    title: "Hilsa season in Chandpur",
    n: 12,
    grad: "g6",
    story: "hilsa",
    storyTitle: "Hilsa glut at Chandpur landing station",
    caps: [
      "Fishermen unload the morning hilsa catch at Chandpur",
      "A trader weighs hilsa at the landing station",
      "Crates of hilsa are loaded onto Dhaka-bound trucks",
      "Buyers inspect the catch at the dawn auction",
    ],
  },
  {
    id: "gal2",
    title: "Monsoon lashes Sylhet",
    n: 9,
    grad: "g5",
    story: "sylhet",
    storyTitle: "Sylhet flood situation worsens",
    caps: [
      "A boy wades through a flooded street in Sylhet",
      "Houses half-submerged near the Surma river",
      "Residents move their belongings by boat",
      "Relief teams reach a cut-off village",
    ],
  },
  {
    id: "gal3",
    title: "Tigers gear up for the Test",
    n: 14,
    grad: "g3",
    story: "tigers",
    storyTitle: "Tigers begin Test camp at Mirpur",
    caps: [
      "Tigers fielding drills at Sher-e-Bangla stadium",
      "Shakib Al Hasan bowls during training",
      "Batting practice under lights at Mirpur",
      "The head coach speaks to the squad",
    ],
  },
];

export const COLLECTIONS: CollectionItem[] = [
  { id: "c1", name: "Election 2026", n: 48, grad: "g1", kw: "election" },
  { id: "c2", name: "Monsoon & climate", n: 36, grad: "g5", kw: "flood" },
  { id: "c3", name: "Tigers Test series", n: 27, grad: "g3", kw: "tigers" },
  { id: "c4", name: "Dhaka cityscape", n: 63, grad: "g7", kw: "dhaka" },
];

export const TRENDING: TrendingItem[] = [
  { cap: "Rizvi waves to activists outside the Nayapaltan office", dl: 41 },
  { cap: "Bangladesh women celebrate a wicket in Sylhet", dl: 36 },
  { cap: "Bangla QR payment at a New Market shop", dl: 33 },
  { cap: "The president places a wreath at the National Memorial", dl: 28 },
  { cap: "New greenery on the Bishkhali riverbanks", dl: 22 },
];

export const STORY_TITLES: Record<string, string> = {
  hilsa: "Hilsa glut at Chandpur landing station",
  tigers: "Tigers begin Test camp at Mirpur",
  padma: "Padma Bridge traffic crosses record",
};

export const PHOTO_STREAM: StreamPhotoItem[] = [
  {
    id: "s1",
    cap: "Morning fog settles over the Buriganga river",
    by: "Rashed Sumon",
    loc: "Dhaka",
    date: "Today, 6:30 AM",
    grad: "g5",
    story: null,
    kw: "buriganga fog",
  },
  {
    id: "s2",
    cap: "Fishermen unload the morning hilsa catch",
    by: "Mahmud Hossain",
    loc: "Chandpur",
    date: "Today, 7:55 AM",
    grad: "g6",
    story: "hilsa",
    kw: "hilsa chandpur fish",
  },
  {
    id: "s3",
    cap: "Tigers fielding drills at Sher-e-Bangla stadium",
    by: "Tuhin Shubhra",
    loc: "Mirpur, Dhaka",
    date: "Yesterday, 3:05 PM",
    grad: "g3",
    story: "tigers",
    kw: "cricket tigers practice",
  },
  {
    id: "s4",
    cap: "Containers stacked high at Chattogram port",
    by: "Mahmud Hossain",
    loc: "Chattogram",
    date: "Yesterday, 11:10 AM",
    grad: "g1",
    story: null,
    kw: "port export trade",
  },
  {
    id: "s5",
    cap: "Street vendors open shop at Karwan Bazar at dawn",
    by: "Mahmud Hossain",
    loc: "Dhaka",
    date: "Yesterday, 5:50 AM",
    grad: "g7",
    story: null,
    kw: "karwan bazar vendors",
  },
  {
    id: "s6",
    cap: "Smog hangs over the Dhaka skyline at dawn",
    by: "Mahmud Hossain",
    loc: "Dhaka",
    date: "19 Aug, 6:10 AM",
    grad: "g4",
    story: null,
    kw: "smog pollution",
  },
  {
    id: "s7",
    cap: "Padma Bridge aerial view — morning traffic",
    by: "Rashed Sumon",
    loc: "Mawa",
    date: "19 Aug, 8:20 AM",
    grad: "g8",
    story: "padma",
    kw: "padma bridge aerial",
  },
  {
    id: "s8",
    cap: "Commuters crowd the launch terminal at Sadarghat",
    by: "Mahmud Hossain",
    loc: "Dhaka",
    date: "21 Aug, 2:15 PM",
    grad: "g2",
    story: null,
    kw: "sadarghat launch commute",
  },
];

export const SAVED_SEARCHES: SavedSearch[] = [
  { name: "election", q: "election" },
  { name: "swapon", q: "swapon" },
  { name: "padma bridge", q: "padma" },
  { name: "cricket", q: "cricket" },
];

export const CLIENT_INFO: ClientContext = {
  name: "Daily Star",
  initials: "DS",
  tier: "Premium",
  renews_at: "1 Oct 2026",
  stories_quota: 500,
  stories_used: 342,
  media_quota: 150,
  media_used: 87,
};
