export const SEL = {
  profile: {
    page: '/profile',
    nameInput: 'input[name="name"]',
    emailInput: 'input[name="email"]',
    saveBtn: 'button:has-text("Save")',
    passwordSection: 'form:has(input[name="password"])',
    currentPassword: 'input[name="current_password"]',
    newPassword: 'input[name="password"]',
    confirmPassword: 'input[name="password_confirmation"]',
    updatePasswordBtn: 'button:has-text("Update password"), button:has-text("Save")',
  },
  preferences: {
    page: '/admin/preferences',
    deskSelect: 'select[wire\\:model="desk"]',
    timezoneSelect: 'select[wire\\:model="timezone"]',
    dateFormatSelect: 'select[wire\\:model="dateFormat"], select[wire\\:model="date_format"]',
    densitySelect: 'select[wire\\:model="density"]',
    saveBtn: 'button:has-text("Save")',
  },
  portal: {
    loginBtn: 'button:has-text("Login")',
    emailInput: 'input[type="email"], input[placeholder*="email" i]',
    passwordInput: 'input[type="password"]',
    submitLoginBtn: 'button[type="submit"]:has-text("Login"), button[type="submit"]:has-text("Log in")',
    forgotPasswordLink: 'a:has-text("Forgot password"), button:has-text("Forgot password")',
    apiKeyLink: 'a:has-text("API key"), button:has-text("API key")',
    logoutBtn: 'button:has-text("Log out"), button:has-text("Logout")',
    myAccountLink: 'a:has-text("My Account"), a[href*="account"]',
    userDropdown: '#userBtn, button:has-text("Premium subscriber"), [class*="user-btn"]',
    userName: '[class*="user-name"], .user-name',
  },
  portalAccount: {
    page: 'http://localhost:3000/account',
    nameDisplay: '[class*="profile-name"], [data-field="name"]',
    emailDisplay: '[class*="profile-email"], [data-field="email"]',
    editBtn: 'button:has-text("Edit"), button:has-text("Update")',
    saveBtn: 'button:has-text("Save")',
    changePasswordBtn: 'button:has-text("Change password"), button:has-text("Update password")',
    currentPassword: 'input[name="current_password"], input[placeholder*="current" i]',
    newPassword: 'input[name="password"], input[placeholder*="new" i]',
    confirmPassword: 'input[name="password_confirmation"], input[placeholder*="confirm" i]',
    backToFeedLink: 'a:has-text("Back to feed"), a:has-text("Back")',
  },
  clients: {
    page: '/admin/clients',
    drawer: '.drawer, [class*="drawer"]',
    portalUsersTab: 'button:has-text("Portal Users"), [data-tab="portal-users"]',
    invitePortalUserBtn: 'button:has-text("Invite portal user"), button:has-text("Invite user")',
    inviteModal: '.modal-overlay.open, [class*="modal"][class*="open"]',
    inviteNameInput: 'input[placeholder*="name" i], input[wire\\:model="portalInviteName"]',
    inviteEmailInput: 'input[placeholder*="email" i], input[type="email"][wire\\:model="portalInviteEmail"]',
    inviteRoleSelect: 'select[wire\\:model="portalInviteRoleId"]',
    sendInviteBtn: 'button:has-text("Send invite")',
    deactivateBtn: 'button:has-text("Deactivate")',
    reactivateBtn: 'button:has-text("Reactivate")',
    resendInviteBtn: 'button:has-text("Resend invite")',
    statusBadge: '[class*="status-badge"], [class*="badge"]',
  },
  topnav: {
    profileLink: 'a[href*="profile"]',
    preferencesLink: 'a[href*="preferences"]',
  },
  sidebar: {
    preferencesLink: 'a[href*="preferences"]',
    clientsLink: 'a[href*="clients"]',
    rolesLink: 'a[href*="roles"]',
  },
} as const;
